<a href="https://colab.research.google.com/github/UgamThakkar/pytorch0-100/blob/main/Pytorch_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.11.0+cpu


In [2]:
if torch.cuda.is_available():
  print("GPu is available")
else:
  print("Using CPU")

Using CPU


In [ ]:
#Ways to Create a tensor


In [3]:
#Using Empty
torch.empty(2,3) #creates a space in the memory and whatever exising value was sitting there prints it out for us

tensor([[3.6022e-12, 7.1223e+28, 3.0958e-18],
        [2.6532e+20, 3.2607e-12, 1.1080e+27]])

In [4]:
#Using Zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
#using rand
torch.rand(2,3) #creates a tensor where all the values are between 0 and 1

tensor([[0.2744, 0.3081, 0.7182],
        [0.5407, 0.4526, 0.5454]])

In [7]:
#using tensor
torch.tensor([[1,2,3], [4,5,6]]) #creates a tensor with the values we want it to have

tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
#using arange
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [9]:
#using eye (identity matrix)
torch.eye(5) #creates a 5x5 identity matrix

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [10]:
#Tensor Shapes
x = torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
x.shape

torch.Size([2, 3])

In [11]:
#if we want to create a similar tensor out of another tensor we can use methods like
torch.empty_like(x)

tensor([[             128961,                  36,                   0],
        [                  0,                   0, 7005408813921809973]])

In [14]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [15]:
#Tensor Datatypes
x.dtype

torch.int64

In [16]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [17]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int64)

tensor([1, 2, 3])

In [19]:
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)